strictness: medium
doc-warnings: false

ignore:
  - import-error

pylint:
  disable:
    - import-error
    - too-many-arguments
    - too-many-positional-arguments
  options:
    max-args: 7

pyflakes:
  disable:
    - F401